
package ru.edu.eo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PushDataServiceSoap", targetNamespace = "http://eo.edu.ru")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PushDataServiceSoap {


    /**
     * 
     * @param parameters
     * @param authentication
     * @return
     *     returns ru.edu.eo.PushZipDataAsyncResponse
     */
    @WebMethod(operationName = "PushZipDataAsync", action = "http://eo.edu.ru/PushZipData")
    @WebResult(name = "PushZipDataAsyncResponse", targetNamespace = "http://eo.edu.ru", partName = "parameters")
    public PushZipDataAsyncResponse pushZipDataAsync(
            @WebParam(name = "PushZipDataAsync", targetNamespace = "http://eo.edu.ru", partName = "parameters")
                    PushZipDataAsync parameters,
            @WebParam(name = "Authentication", targetNamespace = "http://eo.edu.ru", header = true, partName = "Authentication")
                    Authentication authentication);

    /**
     *
     * @param parameters
     * @param authentication
     * @return
     *     returns ru.edu.eo.PushZipDataResponse
     */
    @WebMethod(operationName = "PushZipData", action = "http://eo.edu.ru/PushZipData")
    @WebResult(name = "PushZipDataResponse", targetNamespace = "http://eo.edu.ru", partName = "parameters")
    public PushZipDataResponse pushZipData(
            @WebParam(name = "PushZipData", targetNamespace = "http://eo.edu.ru", partName = "parameters")
                    PushZipData parameters,
            @WebParam(name = "Authentication", targetNamespace = "http://eo.edu.ru", header = true, partName = "Authentication")
                    Authentication authentication);

    /**
     *
     * @param parameters
     * @param authentication
     * @return
     *     returns ru.edu.eo.PushDataResponse
     */
    @WebMethod(operationName = "PushData", action = "http://eo.edu.ru/PushData")
    @WebResult(name = "PushDataResponse", targetNamespace = "http://eo.edu.ru", partName = "parameters")
    public PushDataResponse pushData(
            @WebParam(name = "PushData", targetNamespace = "http://eo.edu.ru", partName = "parameters")
                    PushData parameters,
            @WebParam(name = "Authentication", targetNamespace = "http://eo.edu.ru", header = true, partName = "Authentication")
                    Authentication authentication);

}
