
package ru.edu.eo;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PushDataServiceSoapImplService", targetNamespace = "http://ws.serviceBus.eov2.informika.ru/", wsdlLocation = "http://eotv3.dev.informika.ru:8080/services/pushData?wsdl")
public class PushDataServiceSoapImplService
    extends Service
{

    private final static URL PUSHDATASERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUSHDATASERVICESOAPIMPLSERVICE_EXCEPTION;
    private final static QName PUSHDATASERVICESOAPIMPLSERVICE_QNAME = new QName("http://ws.serviceBus.eov2.informika.ru/", "PushDataServiceSoapImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://eotv3.dev.informika.ru:8080/services/pushData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUSHDATASERVICESOAPIMPLSERVICE_WSDL_LOCATION = url;
        PUSHDATASERVICESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public PushDataServiceSoapImplService() {
        super(__getWsdlLocation(), PUSHDATASERVICESOAPIMPLSERVICE_QNAME);
    }

    public PushDataServiceSoapImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUSHDATASERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public PushDataServiceSoapImplService(URL wsdlLocation) {
        super(wsdlLocation, PUSHDATASERVICESOAPIMPLSERVICE_QNAME);
    }

    public PushDataServiceSoapImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUSHDATASERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public PushDataServiceSoapImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PushDataServiceSoapImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PushDataServiceSoap
     */
    @WebEndpoint(name = "PushDataServiceSoapImplPort")
    public PushDataServiceSoap getPushDataServiceSoapImplPort() {
        return super.getPort(new QName("http://ws.serviceBus.eov2.informika.ru/", "PushDataServiceSoapImplPort"), PushDataServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PushDataServiceSoap
     */
    @WebEndpoint(name = "PushDataServiceSoapImplPort")
    public PushDataServiceSoap getPushDataServiceSoapImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.serviceBus.eov2.informika.ru/", "PushDataServiceSoapImplPort"), PushDataServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUSHDATASERVICESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw PUSHDATASERVICESOAPIMPLSERVICE_EXCEPTION;
        }
        return PUSHDATASERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
