package ru.avers.informica.entities;

import ru.avers.informica.entities.abstraction.CItem;
import ru.avers.informica.entities.dicts.CDict03ContactType;
import ru.avers.informica.entities.dicts.CDict70ContactKind;

import javax.persistence.*;
import java.util.Date;

//TODO нет соответствия в новой БД
/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="CONTACT")
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_CONTACT_ID")
public class Contact extends CItem implements IUchRelated {

    public final static String S_UCH_FIELD = "m_uch";

    @ManyToOne(fetch= FetchType.EAGER)
    @JoinColumn(name="ID_UCH")
    private Uch m_uch;

    @Override
    public Uch getUch() {
        return this.m_uch;
    }

    public void setUch(Uch uch) {
        this.m_uch = uch;
    }

    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name = "ID_PERSON")
    private CPerson m_person;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_CONTACT_TYPE")
    private CDict03ContactType m_contact_type;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_CONTACT_KIND")
    private CDict70ContactKind m_contact_kind;

    @Column(name = "CONTACT")
    private String m_contact;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "DS")
    private Date m_ds;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "DF")
    private Date m_df;

    public Contact() { super(); }
    public Contact(Integer p_id) { super(p_id); }
    public Contact(CDict70ContactKind p_kind, Uch p_uch, String p_contact) { this(null, p_kind, null, p_uch, p_contact); }
    public Contact(Integer p_id, CDict70ContactKind p_kind, Uch p_uch, String p_contact) {
        this(p_id, p_kind, null, p_uch, p_contact);
    }
    public Contact(Integer p_id, CDict70ContactKind p_kind, CDict03ContactType p_type, Uch p_uch, String p_contact) {
       this(p_id);
       setUch(p_uch);
       m_contact_kind = p_kind;
       m_contact_type = p_type;
       m_contact = p_contact;
    }
  
    public CPerson getPerson() {
        return this.m_person;
    }    
    public void setPerson(CPerson p_person) {
        this.m_person = p_person;
    }

    public CDict03ContactType getContactType() {
        return this.m_contact_type;
    }    
    public void setContactType(CDict03ContactType p_value) {
        this.m_contact_type = p_value;
    }

    public CDict70ContactKind getContactKind() {
        return this.m_contact_kind;
    }    
    public void setContactKind(CDict70ContactKind p_value) {
        this.m_contact_kind = p_value;
    }

    public String getContact() {
        return this.m_contact;
    }
    
    public void setContact(String contact) {
        this.m_contact = contact;
    }
    public Date getDs() {
        return this.m_ds;
    }
    
    public void setDs(Date ds) {
        this.m_ds = ds;
    }
    public Date getDf() {
        return this.m_df;
    }
    
    public void setDf(Date df) {
        this.m_df = df;
    }
}
