package ru.avers.informica.entities;

import ru.avers.informica.entities.abstraction.CItem;
import ru.avers.informica.entities.dicts.CDict77InqryStatusReason;

import javax.persistence.*;

/**
 * Inqrystsrsn generated by hbm2java
 */
@Entity
@Table(name="INQRYSTSRSN")  // status_rsn - нова€ таблица (ѕричины установки статуса за€влению)
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_INQRYSTSRSN_ID")
public class Inqrystsrsn extends CItem {

    public final static String S_REASON_NAME = "m_inqry_status_reason.m_name",
                               S_STATUS_ID = "m_inqrystatus.m_id",
                               S_DESCR = "m_descr";

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_INQRYSTATUS")
    private Inqrystatus m_inqrystatus;

    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name="ID_REASON")
    private CDict77InqryStatusReason m_inqry_status_reason;

    @Column(name = "DESCR")
    private String m_descr;

    public Inqrystsrsn() {
    }

    public Inqrystatus getInqrystatus() {
        return this.m_inqrystatus;
    }
    
    public void setInqrystatus(Inqrystatus inqrystatus) {
        this.m_inqrystatus = inqrystatus;
    }

    public CDict77InqryStatusReason getDictsDetail() {
        return this.m_inqry_status_reason;
    }
    
    public void setDictsDetail(CDict77InqryStatusReason p_inqry_status_reason) {
        this.m_inqry_status_reason = p_inqry_status_reason;
    }
    
    public String getDescr() {
        return this.m_descr;
    }
    
    public void setDescr(String descr) {
        this.m_descr = descr;
    }

}
