package ru.avers.informica.entities;

import ru.avers.informica.dao.IMapFields;
import ru.avers.informica.entities.abstraction.CItem;
import ru.avers.informica.entities.entitybymap.IDBMapFields.IInqryuch;

import javax.persistence.*;

/**
 * Inqryuch generated by hbm2java
 */
@Entity
@Table(name="INQRYUCH")  // новая таблица - buildings (Организации в заявлении)
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_INQRYUCH_ID")
public class Inqryuch extends CItem {

    public final static String S_INQRY_ID = IInqryuch.s_inqry,
                               S_INQRY_NUM = IInqryuch.s_inqry + IMapFields.s_field_delimiter + Inqrychldinuch.S_NUM,
                               S_STATUS = "",
                               S_STATUS_SET_DATE = "",
                               S_CHILD_SRNM = IInqryuch.s_inqry + IMapFields.s_field_delimiter + Inqrychldinuch.S_CHLD_SRNM,
                               S_UCH = IInqryuch.s_uch,
                               S_UCH_NAME = IInqryuch.s_uch + IMapFields.s_field_delimiter + Uch.S_NM_FIELD,
                               S_UCH_NUM = IInqryuch.s_uch + IMapFields.s_field_delimiter + Uch.S_NUM_FIELD,
                               S_UCH_SNM = IInqryuch.s_uch + IMapFields.s_field_delimiter + Uch.S_SNM_FIELD,
                               S_UCH_TER_ID = IInqryuch.s_uch + IMapFields.s_field_delimiter + Uch.S_TER_ID_FIELD;

    @ManyToOne(fetch = FetchType.LAZY, optional=false)
    @JoinColumn(name = "ID_INQRY")
    private Inqrychldinuch m_inqrychldinuch;
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_UCH")
    private Uch m_uch;

    @Column(name = "PRTY")
    private Short m_prty;
    
    @Column(name = "DESCR")
    private String m_descr;

    public Inqryuch() { super(); }
    public Inqryuch(Integer p_id) { super(p_id); }

    public Inqrychldinuch getInqrychldinuch() {
        return this.m_inqrychldinuch;
    }
    
    public void setInqrychldinuch(Inqrychldinuch inqrychldinuch) {
        this.m_inqrychldinuch = inqrychldinuch;
    }
    public Uch getUch() {
        return this.m_uch;
    }
    
    public void setUch(Uch uch) {
        this.m_uch = uch;
    }
    
    public Short getPrty() {
        return this.m_prty;
    }
    
    public void setPrty(Short prty) {
        this.m_prty = prty;
    }
    
    public String getDescr() {
        return this.m_descr;
    }
    
    public void setDescr(String descr) {
        this.m_descr = descr;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Inqryuch [");
        builder.append("descr=").append(m_descr);
        builder.append(", inqrychldinuch=").append(m_inqrychldinuch);
        builder.append(", prty=").append(m_prty);
        builder.append(", uch=").append(m_uch);
        builder.append("]");
        return builder.toString();
    }
    
} 