package ru.avers.informica.entities;

import ru.avers.informica.entities.abstraction.CItem;
import ru.avers.informica.entities.dicts.CDict08TypeClass;
import ru.avers.informica.entities.dicts.CDict85DouGrpTime;
import ru.avers.informica.entities.dicts.CDict92OrgStruct;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

 TODO нет пока аналога таблицы в новой БД
/**
 * UchInfo4inqry generated by hbm2java
 */
@Entity
@Table(name="UCH_INFO4INQRY")
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_UCH_INFO4INQRY_ID")
public class UchInfo4inqry extends CItem implements IUchRelated {

    public final static String S_UCH = "m_uch",
                               S_PRLL4STG = "m_prll4stg",
                               S_PRLLTYPE = "m_prll_type",
                               S_STGUCH = S_PRLL4STG + ".m_stage_uch",
                               S_NVACANT = "NVacant";


    @ManyToOne(fetch= FetchType.EAGER)
    @JoinColumn(name="ID_UCH")
    private Uch m_uch;
    public Uch getUch() { return m_uch; }
    public final void setUch(Uch uch) { m_uch = uch; }

    //http://www.mkyong.com/hibernate/cascade-jpa-hibernate-annotation-common-mistake/
    @ManyToOne(fetch= FetchType.EAGER, cascade= CascadeType.ALL)
    @JoinColumn(name="ID_PRLL4STG")
    private Prll4stg m_prll4stg;
    public Prll4stg getPrll4stg() { return m_prll4stg; }
    public final void setPrll4stg(Prll4stg p_prll4stg) { m_prll4stg = p_prll4stg; }
    
    @ManyToOne(fetch= FetchType.EAGER)
    @JoinColumn(name="ID_TCLS")
    private CDict08TypeClass m_prll_type;
    public CDict08TypeClass getPrllType() { return m_prll_type; }
    public final void setPrllType(CDict08TypeClass p_prll_type) { m_prll_type = p_prll_type; }
    
    @ManyToOne
    @JoinColumn(name="ID_DOU_GRP_TIME")
    private CDict85DouGrpTime m_dou_grp_type;
    public CDict85DouGrpTime getDouGrpTime() { return m_dou_grp_type; }
    public final void setDouGrpTime(CDict85DouGrpTime p_val) { m_dou_grp_type = p_val; }
    
    @ManyToOne
    @JoinColumn(name="ID_ORG_STRUCT")
    private CDict92OrgStruct m_dou_org_struct;
    public CDict92OrgStruct getDouOrgStruct() { return m_dou_org_struct; }
    public final void setDouOrgStruct(CDict92OrgStruct p_val) { m_dou_org_struct = p_val; }

    @Column(name="VACANT_YEAR")
    private Integer m_year;
    public Integer getYear() { return m_year; }
    public void setYear(Integer p_year) { m_year = p_year; }

//    2015-09-02 Не используется
//    @Column(name="N_HLTH_ABSENT")
//    private Integer m_cnt_by_health_absent;
//    public Integer getCntByHealthAbsent() { return m_cnt_by_health_absent; }
//    public void setCntByHealthAbsent(Integer p_val) { m_cnt_by_health_absent = p_val; }
    
    @Temporal(TemporalType.DATE)
    @Column(name="DT_TO")
    private Date m_dt_to;
    public Date getDtTo() { return m_dt_to; }
    public void setDtTo(Date p_dt_to) { m_dt_to = p_dt_to; }
    
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "m_uch_info4inqry", orphanRemoval = true)
    private List<Prll4stgAges> m_ages = new ArrayList<Prll4stgAges>(0);
    public List<Prll4stgAges> getAges() { return m_ages; }
    public void setAges(List<Prll4stgAges> p_ages) { m_ages = p_ages; }

    @Column(name="N_PLAN_CLSS")
    private Short NPlanClss;
    public Short getNPlanClss() { return this.NPlanClss; }
    public void setNPlanClss(Short p_val) { this.NPlanClss = p_val; }

    @Column(name="N_VACANT")
    private Short NVacant;
    public Short getNVacant() { return this.NVacant; }
    public void setNVacant(Short p_val) { this.NVacant = p_val; }

    @Column(name="N_VACANT_1")
    private Short m_nvacant_add;
    public Short getNVacantAdd() { return m_nvacant_add; }
    public void setNVacantAdd(Short p_nvacant_add) { m_nvacant_add = p_nvacant_add; }

    @Column(name="N_VACANT_2")
    private Short m_n_fact;
    public Short getNFact() { return m_n_fact; }
    public void setNFact(Short p_val) { m_n_fact = p_val; }
    
    @Column(name = "INFO_1")
    private String info1;

    @Column(name = "INFO_2")
    private String info2;

    @Column(name = "INFO_3")
    private String info3;

    @Column(name = "INFO_4")
    private String info4;

    @Column(name = "INFO_5")
    private String info5;

    @Column(name = "INFO_6")
    private String info6;

    @Column(name = "INFO_7")
    private String info7;

    @Column(name = "INFO_8")
    private String info8;
    
    @Column(name = "INFO_9")
    private String info9;
    
    @Column(name = "INFO_10")
    private String info10;

    @Column(name = "INFO_11")
    private String info11;
    
    @Column(name = "INFO_12")
    private String info12;
    
    @Column(name = "INFO_13")
    private String info13;
    
    @Column(name = "INFO_14")
    private String info14;
    

    public UchInfo4inqry() { super(); }
    public UchInfo4inqry(Integer p_id) { super(p_id); }
    public UchInfo4inqry(Uch p_uch) { this(null, p_uch); }
    public UchInfo4inqry(Integer p_id, Uch p_uch) { this(p_id, p_uch, null, null, null); }
    public UchInfo4inqry(
                        Uch p_uch, 
                        Prll4stg p_prll4stg, 
                        CDict08TypeClass p_prll_type, 
                        CDict85DouGrpTime p_dou_grp_type) {
        this(null, p_uch, p_prll4stg, p_prll_type, p_dou_grp_type);
    }
    public UchInfo4inqry(
                        Integer p_id,
                        Uch p_uch, 
                        Prll4stg p_prll4stg, 
                        CDict08TypeClass p_prll_type, 
                        CDict85DouGrpTime p_dou_grp_type) {
        super(p_id);
        setUch(p_uch);
        setPrll4stg(p_prll4stg);
        setPrllType(p_prll_type);
        setDouGrpTime(p_dou_grp_type);
    }
    
    public String getInfo1() {
        return this.info1;
    }
    
    public void setInfo1(String info1) {
        this.info1 = info1;
    }
    
    public String getInfo2() {
        return this.info2;
    }
    
    public void setInfo2(String info2) {
        this.info2 = info2;
    }
    
    public String getInfo3() {
        return this.info3;
    }
    
    public void setInfo3(String info3) {
        this.info3 = info3;
    }
    
    public String getInfo4() {
        return this.info4;
    }
    
    public void setInfo4(String info4) {
        this.info4 = info4;
    }
    
    public String getInfo5() {
        return this.info5;
    }
    
    public void setInfo5(String info5) {
        this.info5 = info5;
    }
    
    public String getInfo6() {
        return this.info6;
    }
    
    public void setInfo6(String info6) {
        this.info6 = info6;
    }
    
    public String getInfo7() {
        return this.info7;
    }
    
    public void setInfo7(String info7) {
        this.info7 = info7;
    }

    public String getInfo8() {
        return this.info8;
    }
    
    public void setInfo8(String info8) {
        this.info8 = info8;
    }
    
    public String getInfo9() {
        return this.info9;
    }
    
    public void setInfo9(String info9) {
        this.info9 = info9;
    }

    public String getInfo10() {
        return info10;
    }

    public void setInfo10(String info10) {
        this.info10 = info10;
    }

    public String getInfo11() {
        return info11;
    }

    public void setInfo11(String info11) {
        this.info11 = info11;
    }

    public String getInfo12() {
        return info12;
    }

    public void setInfo12(String info12) {
        this.info12 = info12;
    }

    public String getInfo13() {
        return info13;
    }

    public void setInfo13(String info13) {
        this.info13 = info13;
    }

    public String getInfo14() {
        return info14;
    }

    public void setInfo14(String info14) {
        this.info14 = info14;
    }    
    
}
