package ru.avers.informica.entities;

import ru.avers.informica.entities.abstraction.CItem;
import ru.avers.informica.entities.dicts.CDict04MunicipObrazov;
import ru.avers.informica.entities.dicts.CDict06TypeOfSobstven;
import ru.avers.informica.entities.dicts.CDict11TypeOfUch;

import javax.persistence.*;
import java.util.Date;

// TODO нет пока аналога таблицы в новой БД
/**
 * UchVar generated by hbm2java
 */
@Entity
@Table(name="UCH_VAR")
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_UCH_VAR_ID")
public class UchVar extends CItem {

    @ManyToOne(cascade= CascadeType.PERSIST, fetch= FetchType.EAGER)
    @JoinColumn(name="id_fsobstv")
    private CDict06TypeOfSobstven id_fsobstv;

    @ManyToOne(cascade= CascadeType.PERSIST, fetch= FetchType.EAGER)
    @JoinColumn(name="ID_TER")
    private CDict04MunicipObrazov m_ter;

    @ManyToOne(cascade= CascadeType.PERSIST, fetch= FetchType.EAGER)
    @JoinColumn(name="ID_TU")
    private CDict11TypeOfUch m_tu;

    @OneToOne(cascade= CascadeType.ALL, fetch= FetchType.LAZY)
    @JoinColumn(name="ID_UCH", nullable=false)
    private Uch uch;

    @Column(name="NUM")
    private String num;

    @Column(name = "NM")
    private String nm;

    @Column(name = "SNM")
    private String snm;

    @Column(name = "URL")
    private String url;

    @Column(name = "EMAILS")
    private String emails;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "DS")
    private Date ds;

    @Temporal(value = TemporalType.TIMESTAMP)
    @Column(name = "DF")
    private Date df;

    @Column(name = "CHIEF")
    private String chief;
    
    @Column(name = "FOUNDER")
    private String m_founder;
    
    @Column(name = "VOUCHER_PLACE")
    private String m_voucher_place;

    public UchVar() { super(); }
    public UchVar(Uch p_uch) { this(null, p_uch); }
    public UchVar(Integer p_id, Uch p_uch) {
        super(p_id);
        this.uch = p_uch;
    }

    public CDict11TypeOfUch getTu() {
        return m_tu;
    }
    
    public void setTu(CDict11TypeOfUch p_value) {
        m_tu = p_value;
    }

    public CDict04MunicipObrazov getTer() {
        return m_ter;
    }

    public void setTer(CDict04MunicipObrazov p_value)
    {
        m_ter = p_value;
    }

    public Uch getUch() {
        return this.uch;
    }

    public void setUch(Uch uch) {
        this.uch = uch;
    }
    
    public String getNum() {
        return this.num;
    }
    
    public void setNum(String num) {
        this.num = num;
    }
    
    public String getNm() {
        return this.nm;
    }
    
    public void setNm(String nm) {
        this.nm = nm;
    }
    
    public String getSnm() {
        return this.snm;
    }
    
    public void setSnm(String snm) {
        this.snm = snm;
    }
    
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    public String getEmails() {
        return this.emails;
    }
    
    public void setEmails(String emails) {
        this.emails = emails;
    }
    public Date getDs() {
        return this.ds;
    }
    
    public void setDs(Date ds) {
        this.ds = ds;
    }
    public Date getDf() {
        return this.df;
    }
    
    public void setDf(Date df) {
        this.df = df;
    }
    
    public String getChief() {
        return this.chief;
    }
    
    public void setChief(String chief) {
        this.chief = chief;
    }

    public String getFounder() {
        return m_founder;
    }

    public void setFounder(String p_founder) {
        this.m_founder = p_founder;
    }
    
    public String getVoucherPlace() {
        return m_voucher_place;
    }
    
    public void setVoucherPlace(String p_voucher_place) {
        m_voucher_place = p_voucher_place;
    }

    public CDict06TypeOfSobstven getIdFsobstv() {
        return id_fsobstv;
    }

    public void setIdFsobstv(CDict06TypeOfSobstven id_fsobstv) {
        this.id_fsobstv = id_fsobstv;
    }
}
