server:
  port: 8084
  servlet:
    context-path: /app

scheduler:
  start:
    time: 0 23 10 * * ?

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name_here?useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Helsinki2018
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: none

logging:
  level:
    org.springframework.web: ERROR
    ru.leodev: DEBUG
  pattern:
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  file: C://Users//Dmitrenko//Log//informica-report-app.log
  ROOT: DEBUG
