package ru.avers.informica.dao.entities;

import ru.avers.informica.entities.Uch;
import ru.avers.informica.entities.abstraction.CItem;

import javax.persistence.*;

/**
 * InquiryUch generated by hbm2java
 */
@Entity
@Table(name="INQRYUCH")  // buildings - новая таблица (выбранные учреждения в заявлении)
// [вторая реализация TODO]
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_INQRYUCH_ID")
public class InqryUch extends CItem {
    
    public InqryUch() { super(); }
    public InqryUch(Integer p_id) { super(p_id); }

    @ManyToOne(fetch = FetchType.LAZY, optional=false)
    @JoinColumn(name = "ID_INQRY")
    private Inqry m_inqrychldinuch;    
    public Inqry getInqrychldinuch() {
        return this.m_inqrychldinuch;
    }
    public void setInqry(Inqry p_inqry) {
        this.m_inqrychldinuch = p_inqry;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_UCH")
    private Uch m_uch;
    public Uch getUch() {
        return this.m_uch;
    }    
    public void setUch(Uch uch) {
        this.m_uch = uch;
    }
    
    @Column(name = "PRTY")
    private Short m_prty;
    public Short getPrty() {
        return this.m_prty;
    }    
    public void setPrty(Short prty) {
        this.m_prty = prty;
    }
    
} 