package ru.avers.informica.entities.informica;

import ru.avers.informica.entities.abstraction.EntityProp;
import ru.avers.informica.entities.dicts.CDict03ContactType;
import ru.avers.informica.entities.dicts.CDict70ContactKind;

import javax.persistence.*;

/**
 * InformicaUchContact generated by hbm2java
 */
@Entity
@Table(name="CONTACT")
@SequenceGenerator(name="SEQ_GEN", sequenceName="GEN_CONTACT_ID")
@Access(AccessType.PROPERTY)
public class InformicaUchContact extends EntityProp {

    public InformicaUchContact() { super(); }
    public InformicaUchContact(Integer p_id) { super(p_id); }
    
    private InformicaUch m_uch;
    private CDict70ContactKind m_contact_kind;
    private CDict03ContactType m_contact_type;
    private String m_contact;

    @ManyToOne(fetch= FetchType.LAZY)
    @JoinColumn(name="ID_UCH")
    public InformicaUch getUch() {
        return this.m_uch;
    }
    public void setUch(InformicaUch uch) {
        this.m_uch = uch;
    }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_CONTACT_KIND")
    public CDict70ContactKind getContactKind() { return m_contact_kind; }    
    public void setContactKind(CDict70ContactKind p_val) { m_contact_kind = p_val; }
    
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ID_CONTACT_TYPE")
    public CDict03ContactType getContactType() { return m_contact_type; }    
    public void setContactType(CDict03ContactType p_val) { m_contact_type = p_val; }
    
    @Column(name = "CONTACT")
    public String getContact() { return m_contact; }
    public void setContact(String contact) { m_contact = contact; }
    
}
